name: Gerar Gráfico de Contribuição

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - "main"

jobs:
  generate:
    permissions:
      contents: write
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          
          
          # Especifica que o gráfico deve ser construído como "pacman"
          build_with: pacman
          
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg?palette=github-dark

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
