name: Gerar Gráfico de Contribuição Pac-Man

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - "main"

jobs:
  generate:
    permissions:
      contents: write
      
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4


      - name: Gerar Gráfico Pac-Man
        uses: abozanona/pacman-contribution-graph@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER_NAME: ${{ github.repository_owner }}
          
      - name: Corrigir Nomes dos Ficheiros
        run: |
          mv ./contribution/pacman.svg ./contribution/pacman-contribution-graph.svg
          mv ./contribution/pacman-dark.svg ./contribution/pacman-contribution-graph-dark.svg
          
      - name: Publicar para a Branch 'output'
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: contribution
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
